#!/bin/sh
# Copyright (c) 2013 Philippe Charrière aka @k33g_org
#
# All rights reserved. No warranty, explicit or implicit, provided.
#

#export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk<version>.jdk/Contents/Home
#export GOLO_HOME=

JARS_HOME="jars"
LIBS_HOME="libs"


#echo "1- loading jars"
#FIND JARS
if [ -d "$JARS_HOME" ]; then
  JARS=""
  FILES="$(find $JARS_HOME -name '*.jar')" 
  for jar in $FILES
  do
    JARS="$JARS$PWD/$jar "
    #echo "--> $jar"
  done
  #export CLASSPATH_PREFIX=${CLASSPATH_PREFIX}:"$JARS"
fi
#echo "2- loading Golo Libraries"
#FIND GOLO LIBRARIES
LIBS=""
if [ -d "$LIBS_HOME" ]; then
  FILES="$(find $LIBS_HOME -name '*.golo')"
  for gf in $FILES
  do
    LIBS="$LIBS $gf"
    #echo "--> $gf"
  done
fi
#echo "3- running $1"

$GOLO_HOME/bin/golo golo --classpath $JARS --files $LIBS $1

